routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployeesController;
use App\Http\Controllers\TimeZoneController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LangController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
    return redirect('login');
});

Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function () { 


    Route::get('timezone', [TimeZoneController::class, 'indexTimeZone'])->name('timezone');
    Route::get('timezone/change', [TimeZoneController::class, 'setTimeZone'])->name('setTimeZone');

    Route::get('/home', [CompaniesController::class, 'index'])->name('company.index');
    Route::post('/company/submit', [CompaniesController::class, 'store'])->name('company.store');
    Route::get('/company/{company}', [CompaniesController::class, 'show'])->name('company.show');
    Route::get('/company/{company}/edit', [CompaniesController::class, 'edit'])->name('company.edit');
    Route::patch('/company/{company}/update', [CompaniesController::class, 'update'])->name('company.update');
    Route::delete('/company/{company}', [CompaniesController::class, 'destroy'])->name('company.destroy');
    Route::get('/list/{company}', [CompaniesController::class, 'showEmployees'])->name('showEmployees');
    

    Route::get('/employee', [EmployeesController::class, 'index'])->name('employee.index');
    Route::post('/employee/submit', [EmployeesController::class, 'store'])->name('employee.store');
    Route::get('/employee/{employee}', [EmployeesController::class, 'show'])->name('employee.show');
    Route::get('/employee/{employee}/edit', [EmployeesController::class, 'edit'])->name('employee.edit');
    Route::put('/employee/{employee}/update', [EmployeesController::class, 'update'])->name('employee.update');
    Route::delete('/employee/{employee}', [EmployeesController::class, 'destroy'])->name('employee.destroy');



   
    Route::resource('items', ItemController::class);
    Route::resource('sells', SellController::class);
    Route::resource('sell-summary', SellSummaryController::class);
    Route::post('summary-per-day', [SellSummaryController::class, 'show'])->name('sellsummary.show');
    Route::get('summary-per-employee/{employee}', [SellSummaryController::class, 'summaryPerEmployee'])->name('perEmployee');

});


Route::get('tes', [EmployeesController::class, 'tes']);

Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/{company}/list-employee', [EmployeesController::class, 'apiShowEmployee']);
});




Route::get('/token/{company}', [CompaniesController::class, 'generateCompanyToken'])->name('showEmployees');



Route::get('wa', [CompaniesController::class, 'whatsapp'])->name('whatsapp');

app/Models/Sell.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sell extends Model
{
    use HasFactory;


    protected $fillable = ['item', 'price', 'discount', 'employee', 'created_date'];
}

app/Http/Controllers/SellController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Sell;
use App\Models\SellSummary;
use App\Models\Item;
use App\Models\Employee;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Http;
use DataTables;
use symfony\Component\HttpFoundation\Response;


class SellController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    	
    	$listItem = Item::all();
    	$listEmployee = Employee::all();
    	$sell = Sell::join('items', 'items.id', '=', 'sells.item')
    		->join('employees', 'employees.id', '=', 'sells.employee')
    		->get(['sells.*', 'items.name', 'employees.first_name', 'employees.last_name']);
    	// dd($sell);
    	$data = [
    		'items' => $sell
    	];

    	if ($request->ajax())
    	{
    		$data = Sell::all();

	    	return Datatables::of($data)
	    		->editColumn('employee', function($row) {
	    			DB::raw("CONCAT(employees.first_name,' ',employees.last_name");
	    		})
	    		->editColumn('created_at', function($row) {
	    			return $row->created_at->timezone(auth()->user()->timezone)->toDateTime();
	    		})
	    		->addIndexColumn()
	    		->addColumn('action', function($row) {
	                   $action_btn = '<a href="'.route('sells.show', $row->id).'" class="btn btn-primary btn-sm">Detail</a>';
	                   return $action_btn;  
	    		})
	    		->rawColumns(['action'])
	    		->make(true);

    	}
    	return view('sells.index', $data, compact('listItem', 'listEmployee'));
    }

    public function store(Request $request)
    {
    	$request->validate([
    		'item'		=> 'required',
    		'price'		=> 'required|numeric',
    		'discount'	=> 'required|numeric',
    		'employee'	=> 'required',
    	]);

    	Sell::create([
    		'item'		=> $request->item,
    		'price'		=> $request->price,
    		'discount'	=> $request->discount,
    		'employee'	=> $request->employee,
    		'created_date' => Carbon::now()
    	]);

    	$sell = SellSummary::where('employee', $request->employee)->first();
    	if (!$sell) {
    		SellSummary::create([
    			'date' 		=> carbon::now(),
    			'employee'	=> $request->employee,
    			'created_date' => Carbon::now(),
    			'last_update'  => Carbon::now(),
    			'price_total'  => $request->price,
    			'discount_total' => ($request->discount / 100) * $request->price,
    			'total'		=> $request->price - (($request->discount / 100) * $request->price)
    		]);
    	}

    	return redirect('sells');
    }

    public function show(Sell $sell)
    {
    	$sell = Sell::find($sell);
        $sell2 = Sell::join('items', 'items.id', '=', 'sells.item')
            ->join('employees', 'employees.id', '=', 'sells.employee')
            ->get(['sells.*', 'items.name', 'items.price', 'employees.first_name', 'employees.last_name']);

        $data = [
            'sell'  => $sell,
            'sell2' => $sell2
        ];
    	return view('sells.show', $data);
    }

    public function edit($id)
    {
        $sell = Sell::find($id);
        $listEmployee = Employee::all();  
        $listItem = Item::all();  
        return view('sells.edit', compact('sell', 'listEmployee', 'listItem'));
    }

    public function update(Request $request, $id)
    {
        $sell = Sell::find($id);
        $request->validate([
            'item'      => 'required',
            'price'     => 'required|numeric',
            'discount'  => 'required',
            'employee'  => 'required',
        ]);

        $sell->update([
            'item' => $request->item,
            'price' => $request->price,
            'discount' => $request->discount,
            'employee' => $request->employee,
        ]);
        
        return redirect()->route('sells.index', $sell);
    }

    public function destroy(Sell $sell)
    {
        Sell::destroy($sell->id);
        return redirect()->route('sells.index');
    }
}

resources/views/sells/edit.blade.php
@extends('layouts.master')


@section('main-menu')
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <div class="panel panel-profile">
                        <div class="clearfix">
                            <!-- LEFT COLUMN -->
                            <div class="profile-left">
                                <!-- PROFILE HEADER -->
                                <div class="profile-header">
                                    <div class="overlay"></div>

                                    <div class="profile-stat">
                                        <div class="row">
  
                                        </div>
                                    </div>
                                </div>
                                
                                
                                <div class="profile-detail">
                                    <div class="profile-info">
                                        <h4 class="heading">{{ trans('sells.info'); }}</h4>
                                        <ul class="list-unstyled list-justify">
                                            <li>Item<span>{{ $sell->item }}</span></li> 
                                            <li>Price <span>{{ $sell->price }}</span></li>
                                            <li>Discount <span>{{ $sell->discount }}</span></li>
                                            <li>Employee <span>{{ $sell->employee }}</span></li>                            
                                            <li>Created Date <span>{{ $sell->created_date }}</span></li>  
                                        </ul>   
                                    </div> 
       
                                    <form action="{{ route('sells.destroy', $sell->id) }}" method='post'> 
                                        @method('delete') 
                                        @csrf
                                        <button class="text-center" type='submit'><a class='btn btn-danger'>{{ trans('sells.delete'); }}</a></button>
                                    </form>
                                </div>
                                
                                
                            </div>
                            
                            <div class="profile-right">
                                <h4 class="heading">{{ trans('sells.edit'); }}</h4>

                                <form action="{{ route('sells.update', ['sell' => $sell->id]) }}" method="post" enctype="multipart/form-data">
                                    @method('patch')
                                    @csrf
                                    <div class="awards">
                                        <div class="row">
                                            <label for="item">Item</label>
                                            <div class="col-md-12 col-sm-12">
                                                <select class="form-control" id="item" name="item">
                                                    @foreach($listItem as $idItem => $item)
                                                    <option value="{{ $idItem }}" class="form-control">{{ $item->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <label for="price">Price</label>
                                            <div class="col-md-12 col-sm-12">
                                                <input type="text" class="form-control @error ('price') is-invalid @enderror" id="price" name="price" aria-describedby="emailHelp" value="{{ $sell->price }}">
                                            </div>
                                        </div>

                                        <div class="row">
                                            <label for="discount">Discount</label>
                                            <div class="col-md-12 col-sm-12">
                                                <input type="text" class="form-control @error ('discount') is-invalid @enderror" id="discount" name="discount" aria-describedby="emailHelp" value="{{ $sell->discount }}">
                                            </div>
                                        </div>

                                        <div class="row">
                                            <label for="employee">Employee</label>
                                            <div class="col-md-12 col-sm-12">
                                                <select class="form-control" id="employee" name="employee">
    				                            @foreach($listEmployee as $idEmployee => $employee)
    				                            	<option value="{{$idEmployee}}">{{ $employee->first_name }} {{ $employee->last_name }}</option>
    				                            @endforeach
                                                </select>
                                            </div>
                                        </div>                                        

                                    </div>
                                    <button type="submit" class="btn btn-primary">Update</button>

                                </form>
                            	

                            </div>
                            <!-- END RIGHT COLUMN -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
@stop

resources/views/sells/index.blade.php
@extends('layouts.master')

@section('main-menu')
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <h3 class="page-title"></h3>
                    <div id="toastr-demo" class="panel">
                        <div class="panel-body">
                            @if(session('status'))
                                <div class="alert alert-success text-center" role="alert">
                                    {{session('status')}}
                                </div>
                            @endif
                                <h2 class="text-center">{{ trans('items.list'); }}</h1></h2>

                                    <!-- CONDENSED TABLE -->
                                    <div class="panel">
                                        <div class="col-6">
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                                {{ trans('validation.btn_add'); }}
                                            </button>
                                        </div>
                                        <div class="panel-body">
                                            <table class="table table-condensed table-hover" id="">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Item</th>
                                                        <th>Price</th>
                                                        <th>Discount</th>
                                                        <th>Employee</th>
                                                        <th>Created At</th>
                                                        <th>Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                	
                                            		@foreach($items as $data)
                                                    <tr>
                                                        <td>{{ $loop->iteration }}</td>
                                                        <td>{{ $data->name }}</td>
                                                        <td>{{ $data->price }}</td>
                                                        <td>{{ $data->discount }}</td>
                                                        <td>{{ $data->first_name }} {{ $data->last_name }}</td>
                                                        <td>{{ $data->created_date }}</td>
                                                        <td>
		                                                    <form action="{{ route('sells.update', $data->id) }}">
																
																<button type='submit' class='btn btn-info btn-sm' data-toggle="modal" data-target="#desc">Details</button>
															</form>
														</td>
                                                    </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>      
@stop







<!-- Modal Add -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{ trans('items.create'); }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>


                </div>
                <div class="modal-body">
                    <form action="{{ route('sells.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="item">Item</label>
                            <select class="form-control" name="item" id="withPrice">
                            {{-- <!-- @foreach($listItem as $idItem => $item) --> --}}
                            @foreach($listItem as $data)
                                <option value={{$data->id}} data-price ="{{$data->price}}" id="itemPrice">{{ $data->name }}</option>
                            {{--	<!-- <option value="{{$idItem}}">{{ $item }}</option> -->  --}}
                            @endforeach
                        	</select>


                            @error ('item')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="price">Price</label>
                            <input type="text" id="price_item" class="form-control @error ('price') is-invalid @enderror" name="price" placeholder="{{__('price')}}..." value="{{ old('price') }}" >
                            {{--
                            <select class="form-control" id="price_item" name="price">
                            @foreach($listItem as $item)
                                <option value="{{ $item->price }}" id="price_item">{{ $item->price }}</option>
                            <option value="">{{ $item }}</option>
                            @endforeach
                        	</select>
                            --}}
                            
                            @error ('price')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="discount">Discount</label>
                            <input value="6" type="text" class="form-control @error ('discount') is-invalid @enderror" id="discount" name="discount" value="{{ old('discount') }}">

                            @error ('discount')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>


                        <div class="form-group">
                            <label for="item">Employee</label>
                            <select class="form-control" id="employee" name="employee">
                            @foreach($listEmployee as $employee)
                            	<option value="{{$employee->id}}">{{ $employee->first_name }} {{ $employee->last_name }}</option>
                            @endforeach
                        	</select>

                            @error ('item')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ trans('validation.btn_close'); }}</button>
                        <button type="submit" class="btn btn-primary">{{ trans('validation.btn_submit'); }}</button>
                    </form>
            </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src = "http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js" defer ></script>

    


<script type="text/javascript">
    $(document).ready(function() {
        var table = $('#itemTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('sells.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'item', name: 'item'},
                {data: 'price', name: 'price'},
                {data: 'discount', name: 'discount'},
                {data: 'employee', name: 'employee'},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script src="//cdn.datatables.net/plug-ins/1.10.25/pagination/input.js"></script>


<script type="text/javascript">
        const itemPrice = document.getElementById("withPrice");
        itemPrice.onchange = function(e){
            const price = e.target.options[e.target.selectedIndex].dataset.price;
            console.log(price);
            document.getElementById("price_item").value = price
        }
</script>

resources/views/sells/show.blade.php
@extends('layouts.master')


@section('main-menu')
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <div class="panel panel-profile">
                        <div class="clearfix">
                            <!-- LEFT COLUMN -->
                            <div class="profile-left">
                                <!-- PROFILE HEADER -->
                                <div class="profile-header">
                                    <div class="overlay"></div>
                                    

                                    @foreach($sell as $data)

                                    <div class="profile-stat">
                                        <div class="row">

                                        </div>
                                    </div>
                                </div>
                                
                                <div class="profile-detail">
                                    <div class="profile-info">
                                        <h1></h1>
                                        <h4 class="heading">{{ trans('sells.info'); }}</h4>
                                
                                        <ul class="list-unstyled list-justify">
                                            <li>Item<span>{{ $data->item }}</span></li>
                                            <li>Price<span>{{ $data->price }}</span></li>
                                            <li>Discount<span>{{ $data->price }}</span></li>
                                            @foreach($sell2 as $data)
                                            <li>Employee<span>{{ $data->first_name }} {{ $data->last_name }}</span></li>
                                            @endforeach
                                            <li>Created Date<span>{{ $data->created_date }}</span></li>
                                        </ul>
                                        
                                    </div> 


                                    <div class="text-center"><a href="{{ route('sells.edit', $data->id) }}" class="btn btn-primary">{{ trans('sells.edit'); }}</a></div>
                                @endforeach
                                </div>     

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
@stop