routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployeesController;
use App\Http\Controllers\TimeZoneController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LangController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
    return redirect('login');
});

Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function () { 


    Route::get('timezone', [TimeZoneController::class, 'indexTimeZone'])->name('timezone');
    Route::get('timezone/change', [TimeZoneController::class, 'setTimeZone'])->name('setTimeZone');

    Route::get('/home', [CompaniesController::class, 'index'])->name('company.index');
    Route::post('/company/submit', [CompaniesController::class, 'store'])->name('company.store');
    Route::get('/company/{company}', [CompaniesController::class, 'show'])->name('company.show');
    Route::get('/company/{company}/edit', [CompaniesController::class, 'edit'])->name('company.edit');
    Route::patch('/company/{company}/update', [CompaniesController::class, 'update'])->name('company.update');
    Route::delete('/company/{company}', [CompaniesController::class, 'destroy'])->name('company.destroy');
    Route::get('/list/{company}', [CompaniesController::class, 'showEmployees'])->name('showEmployees');
    

    Route::get('/employee', [EmployeesController::class, 'index'])->name('employee.index');
    Route::post('/employee/submit', [EmployeesController::class, 'store'])->name('employee.store');
    Route::get('/employee/{employee}', [EmployeesController::class, 'show'])->name('employee.show');
    Route::get('/employee/{employee}/edit', [EmployeesController::class, 'edit'])->name('employee.edit');
    Route::put('/employee/{employee}/update', [EmployeesController::class, 'update'])->name('employee.update');
    Route::delete('/employee/{employee}', [EmployeesController::class, 'destroy'])->name('employee.destroy');



   
    Route::resource('items', ItemController::class);
    Route::resource('sells', SellController::class);
    Route::resource('sell-summary', SellSummaryController::class);
    Route::post('summary-per-day', [SellSummaryController::class, 'show'])->name('sellsummary.show');
    Route::get('summary-per-employee/{employee}', [SellSummaryController::class, 'summaryPerEmployee'])->name('perEmployee');

});


Route::get('tes', [EmployeesController::class, 'tes']);

Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/{company}/list-employee', [EmployeesController::class, 'apiShowEmployee']);
});




Route::get('/token/{company}', [CompaniesController::class, 'generateCompanyToken'])->name('showEmployees');



Route::get('wa', [CompaniesController::class, 'whatsapp'])->name('whatsapp');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
  
    protected $fillable = ['name', 'price'];
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use DataTables;


class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    	
    	if ($request->ajax()) {
    		$data = Item::all();
            // foreach ($data as $d) {
            //     $d->created_at =  \Carbon\Carbon::parse($d->created_at->timezone(auth()->user()->timezone))->toDateTime();
            // }
    		
            return Datatables::of($data)
                    ->editColumn('created_at', function($row) {
                     return $row->created_at->timezone(auth()->user()->timezone)->toDateTime();
                    })
                    ->addIndexColumn()
                    ->addColumn('action', function($row) {
 
                           $action_btn = '<a href="'.route('items.show', $row->id).'" class="btn btn-primary btn-sm">Detail</a>';
                           return $action_btn;
                           
                    })
                    ->rawColumns(['action'])
                    ->make(true);
    	}
    	return view('items.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    	$request->validate([
    		'name'	=> 'required',
    		'price' => 'required|numeric',
    	]);

    	Item::create([
    		'name'	=> $request->name,
    		'price' => $request->price,
    	]);

    	return redirect()->route('items.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        $items = Item::find($item);
        return view('items.show', compact('items'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view ('items.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $request->validate([
            'name'  => 'required',
            'price' => 'required|numeric',
        ]);

        $item->update($request->all());

        return redirect()->route('items.show', $item);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        Item::destroy($item->id);
        return redirect()->route('items.index');
    }
}

resources/views/items/edit.blade.php
@extends('layouts.master')


@section('main-menu')
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <div class="panel panel-profile">
                        <div class="clearfix">
                            <!-- LEFT COLUMN -->
                            <div class="profile-left">
                                <!-- PROFILE HEADER -->
                                <div class="profile-header">
                                    <div class="overlay"></div>

                                    <div class="profile-stat">
                                        <div class="row">
  
                                        </div>
                                    </div>
                                </div>
                                
                                
                                <div class="profile-detail">
                                    <div class="profile-info">
                                        <h4 class="heading">{{ trans('items.info'); }}</h4>
                                
                                        <ul class="list-unstyled list-justify">
                                            <li>Name<span>{{ $item->name }}</span></li>
                                            <li>Price <span>{{ $item->price }}</span></li>
                                        </ul>
                                        
                                    </div> 

                                    
                                    <form action="{{ route('items.destroy', $item->id) }}" method='post'> 
                                        @method('delete') 
                                        @csrf
                                        <button class="text-center" type='submit'><a class='btn btn-danger'>{{ trans('items.delete'); }}</a></button>
                                    </form>
                                </div>
                                
                                
                            </div>
                            
                            <div class="profile-right">
                                <h4 class="heading">{{ trans('items.edit'); }}</h4>

                                <form action="{{ route('items.update', ['item' => $item->id]) }}" method="post" enctype="multipart/form-data">
                                    @method('patch')
                                    @csrf
                                    <div class="awards">
                                        <div class="row">
                                            <label for="name">Name</label>
                                            <div class="col-md-12 col-sm-12">
                                                
                                                <input type="text" class="form-control @error ('name') is-invalid @enderror" id="name" name="name" aria-describedby="emailHelp" value="{{ $item->name }}">
                                            </div>
                                        </div>

                                        <div class="row">
                                            <label for="price">Price</label>
                                            <div class="col-md-12 col-sm-12">
                                                <input type="text" class="form-control @error ('price') is-invalid @enderror" id="price" name="price" aria-describedby="emailHelp" value="{{ $item->price }}">
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Update</button>

                                </form>
                            

                            </div>
                            <!-- END RIGHT COLUMN -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
@stop

resources/views/items/index.blade.php
@extends('layouts.master')

@section('main-menu')
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <h3 class="page-title"></h3>
                    <div id="toastr-demo" class="panel">
                        <div class="panel-body">
                            @if(session('status'))
                                <div class="alert alert-success text-center" role="alert">
                                    {{session('status')}}
                                </div>
                            @endif
                                <h2 class="text-center">{{ trans('items.list'); }}</h1></h2>

                                    <!-- CONDENSED TABLE -->
                                    <div class="panel">
                                        <div class="col-6">
                                            <!-- Button trigger modal -->
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addItem">
                                                {{ trans('validation.btn_add'); }}
                                            </button>
                                        </div>
                                        <div class="panel-body">
                                            <table class="table table-condensed table-hover" id="itemTable">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Name</th>
                                                        <th>Price</th>
                                                        <th>Created At</th>
                                                        <th>Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                            {{-- <!--         @foreach($data as $item)
                                                    <tr>
                                                        <td>{{ $loop->iteration }}</td>
                                                        <td>{{ $item->name }}</td>
                                                        <td>{{ $item->price }}</td>
                                                    </tr>
                                                    @endforeach --> --}}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
@stop






<!-- Modal Add -->
<div class="modal fade" id="addItem" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{ trans('items.create'); }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>


                </div>
                <div class="modal-body">
                    <form action="{{ route('items.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input value="barang1" type="text" class="form-control @error ('name') is-invalid @enderror" id="name" name="name" aria-describedby="emailHelp" value="{{ old('name') }}">

                            @error ('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label for="price">Price</label>
                            <input value="10.000" type="text" class="form-control @error ('price') is-invalid @enderror" id="price" name="price" aria-describedby="emailHelp" value="{{ old('price') }}">

                            @error ('price')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ trans('validation.btn_close'); }}</button>
                        <button type="submit" class="btn btn-primary">{{ trans('validation.btn_submit'); }}</button>
                    </form>
            </div>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src = "http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js" defer ></script>

    


<script type="text/javascript">
    $(document).ready(function() {
        var table = $('#itemTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('items.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'name', name: 'name'},
                {data: 'price', name: 'price'},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>

resources/views/items/show.blade.php
@extends('layouts.master')


@section('main-menu')
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <div class="panel panel-profile">
                        <div class="clearfix">
                            <!-- LEFT COLUMN -->
                            <div class="profile-left">
                                <!-- PROFILE HEADER -->
                                <div class="profile-header">
                                    <div class="overlay"></div>
                                    

                                    @foreach($items as $data)

                                    <div class="profile-stat">
                                        <div class="row">

                                        </div>
                                    </div>
                                </div>
                                
                                <div class="profile-detail">
                                    <div class="profile-info">
                                        <h1></h1>
                                        <h4 class="heading">{{ trans('items.info'); }}</h4>
                                
                                        <ul class="list-unstyled list-justify">
                                            <li>Name<span>{{ $data->name }}</span></li>
                                            <li>Email <span>{{ $data->price }}</span></li>
                                            
                                        </ul>
                                        
                                    </div> 


                                    <div class="text-center"><a href="{{ route('items.edit', $data->id) }}" class="btn btn-primary">{{ trans('items.edit'); }}</a></div>
                                @endforeach
                                </div>     

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
@stop