routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployeesController;
use App\Http\Controllers\TimeZoneController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LangController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SellController;
use App\Http\Controllers\SellSummaryController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', function () {
    return redirect('login');
});

Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

Auth::routes(['register' => false]);

Route::group(['middleware' => 'auth'], function () { 


    Route::get('timezone', [TimeZoneController::class, 'indexTimeZone'])->name('timezone');
    Route::get('timezone/change', [TimeZoneController::class, 'setTimeZone'])->name('setTimeZone');

    Route::get('/home', [CompaniesController::class, 'index'])->name('company.index');
    Route::post('/company/submit', [CompaniesController::class, 'store'])->name('company.store');
    Route::get('/company/{company}', [CompaniesController::class, 'show'])->name('company.show');
    Route::get('/company/{company}/edit', [CompaniesController::class, 'edit'])->name('company.edit');
    Route::patch('/company/{company}/update', [CompaniesController::class, 'update'])->name('company.update');
    Route::delete('/company/{company}', [CompaniesController::class, 'destroy'])->name('company.destroy');
    Route::get('/list/{company}', [CompaniesController::class, 'showEmployees'])->name('showEmployees');
    

    Route::get('/employee', [EmployeesController::class, 'index'])->name('employee.index');
    Route::post('/employee/submit', [EmployeesController::class, 'store'])->name('employee.store');
    Route::get('/employee/{employee}', [EmployeesController::class, 'show'])->name('employee.show');
    Route::get('/employee/{employee}/edit', [EmployeesController::class, 'edit'])->name('employee.edit');
    Route::put('/employee/{employee}/update', [EmployeesController::class, 'update'])->name('employee.update');
    Route::delete('/employee/{employee}', [EmployeesController::class, 'destroy'])->name('employee.destroy');



   
    Route::resource('items', ItemController::class);
    Route::resource('sells', SellController::class);
    Route::resource('sell-summary', SellSummaryController::class);
    Route::post('summary-per-day', [SellSummaryController::class, 'show'])->name('sellsummary.show');
    Route::get('summary-per-employee/{employee}', [SellSummaryController::class, 'summaryPerEmployee'])->name('perEmployee');

});


Route::get('tes', [EmployeesController::class, 'tes']);

Route::group(['middleware' => ['jwt.verify']], function() {
    Route::get('/{company}/list-employee', [EmployeesController::class, 'apiShowEmployee']);
});




Route::get('/token/{company}', [CompaniesController::class, 'generateCompanyToken'])->name('showEmployees');



Route::get('wa', [CompaniesController::class, 'whatsapp'])->name('whatsapp');

resources/views/layouts/includes/navbar.blade.php
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="brand">
		<a href="index.html"><img src="{{ asset('assets/img/companies_logos.jpg') }}" alt="Logo" class="img-responsive logo" style="height: 30px;"></a>
	</div>
	<div class="container-fluid">
		<div class="navbar-btn">
			<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
		</div>
		<div id="navbar-menu">

			<ul>
				<ul class="col-md-2 col-md-offset-5 text-right">
		            <strong>{{ trans('validation.s.lang'); }}</strong>
		        </ul>
		        <ul class="col-md-2">
		            <select onchange="if (this.value) window.location.href=this.value" class="form-control">
		                <option value="{{ url('locale/en') }}">English</option>
		                <option value="{{ url('locale/id') }}">Indonesia</option>
		            </select>
		        </ul>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ asset('assets/img/user.png') }}" class="img-circle" alt="Avatar"> <span>{{ auth()->user()->name }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
					<ul class="dropdown-menu">
						<!-- <li><a href=""><i class="lnr lnr-user"></i> <span>{{ Auth::user()->lang == 'en' ? 'My Profile' : 'Profil Saya' }}</span></a></li> -->
						<li><a href="{{ route('logout') }}" 
								onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                        <i class="lnr lnr-exit"></i> <span>{{ Auth::user()->lang == 'en' ? 'Logout' : 'Keluar' }}</span></a></li>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

resources/views/layouts/includes/sidebar.blade.php
<div id="sidebar-nav" class="sidebar">
	<div class="sidebar-scroll">
		<nav>
			<ul class="nav">
				
				<li><a href="{{ route('company.index') }}" class="{{ Request::is('home') ? 'active' : '' }}"><i class="lnr lnr-home"></i> <span>{{ trans('validation.company'); }}</span></a></li>
				<li><a href="{{ route('employee.index') }}" class="{{ Request::is('employee') ? 'active' : '' }}"><i class="lnr lnr-user"></i> <span>{{ trans('validation.employee'); }}</span></a></li>

				<li><a href="{{ route('timezone') }}" class="{{ Request::is('timezone') ? 'active' : '' }}"><i class="lnr lnr-clock"></i> <span>{{ trans('validation.timezone'); }}</span></a></li>

				<li><a href="{{ route('items.index') }}" class="{{ Request::is('items') ? 'active' : '' }}"><i class="lnr lnr-tag"></i> <span>{{ trans('validation.items'); }}</span></a></li>
				
				<li><a href="{{ route('sells.index') }}" class="{{ Request::is('sells') ? 'active' : '' }}"><i class="lnr lnr-cart"></i> <span>{{ trans('validation.sells'); }}</span></a></li>

				<li><a href="{{ route('sell-summary.index') }}" class="{{ Request::is('sell-summary') ? 'active' : '' }}"><i class="lnr lnr-database"></i> <spanS>Sell Summary</span></a></li>

<!-- 				<li>
					<a href="#subPages" data-toggle="collapse" class="{{ Request::is('sell-summary') ? 'active' : '' }}"><i class="lnr lnr-book"></i> <span>{{ trans('validation.sell_summary'); }}</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
					<div id="subPages" class="collapse">

						<ul class="nav" id="subPages" class="collapse"> 
							<li><a href="{{ route('sell-summary.index') }}" class="{{ Request::is('sell-summary') ? 'active' : '' }}"><i class="lnr lnr-boox"></i> <span>{{ trans('validation.daily') }}</span></a></li>
							
						</ul>
					</div>
				</li> -->
			</ul>
		</nav>
	</div>
</div>